apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
    replicas: 1
    selector:
      matchLabels:
        app: location
    template:
      metadata:
        labels:
          app: location
      spec:
        containers:
        - name: location
          image: 192.168.56.3:5000/location-service
          imagePullPolicy: Always
          command: [ "python3", "__main__.py" ]
          ports:
          - containerPort: 8080
          env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: connection-string
                key: connection_string
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-password
                key: sa_password

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: location
spec:
  ports:
  - port: 8081
    nodePort: 30700
    protocol: TCP
    targetPort: 8081
  selector:
    app: location
  type: NodePort
status:
  loadBalancer: {}
